version: '3'

networks:
  web-network:
    external: true

services:
  2solar-nginx:
    build:
      context: .docker/nginx
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./app:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  2solar-php:
    build:
      context: .docker/php
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - web-network
